apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ template "todo.fullname" . }}-todo
  name: todo-api-gateway
  labels:
    todo-app-deployment: todo-api-gateway
spec:
  replicas: {{ .Values.replicas.todoApiGateway }}
  selector:
      matchLabels:
        todo-app-pod: todo-api-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-api-gateway
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nslookup todo-rabbitmq; do echo waiting for RabbitMQ; sleep 2; done;']
      containers:
      - name: todo-api-gateway
        image: {{ .Values.todoImageUser }}/todo-api-gateway:{{ .Values.todoVersion }}
        envFrom:
          - configMapRef:
              name: todo-config
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "134217728"

