apiVersion: v1
kind: PersistentVolume
metadata:
 name: elastic-data-pv
 labels:
   type: local
spec:
 storageClassName: manual
 capacity:
   storage: 100Mi
 accessModes:
   - ReadWriteOnce
 hostPath:
   path: "~/todo-app/kubedata/todo/elastic"
