apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: todo
  name: elastic-data-pvc
spec:
#  storageClassName: manual   we would be using the default hostpath for dynamic
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
